# Generated by Django 6.1 on 2026-09-13 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('start_year', models.PositiveBigIntegerField()),
                ('end_year', models.PositiveBigIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
